[package]
name = "densearray"
version = "0.1.0"
authors = ["Peter Jin <peterhaijin@gmail.com>"]

[lib]
name = "densearray"
path = "src/lib.rs"

[dependencies]
densearray_kernels = { path = "kernels" }
byteorder = "^0.5"
openblas_ffi = "^0.1"
