[package]
name = "densearray_kernels"
version = "0.0.1"
authors = ["Peter Jin <peterhaijin@gmail.com>"]
license = "BSD-2-Clause"
description = "densearray_kernels"
build = "build.rs"

[lib]
name = "densearray_kernels"
path = "lib.rs"

[build-dependencies]
gcc = "^0.3"

[dependencies]
libc = "^0.2"
